### ISSUE TITLE
Intellij missing bar character

### ISSUE THREAD

**Issue by cdalexndr** [asarkar/build-time-tracker#19]
Intellij gradle build shows `?` chars instead of bars.
```
 :backend:commons:compileJava | 2S | 12% | ??
  :backend:server:flywayClean | 4S | 24% | ????
:backend:server:flywayMigrate | 5S | 29% | ?????
  :backend:server:compileJava | 1S |  6% | ?
              :web:npmInstall | 1S |  6% | ?
```
Still informative, but looks bad.

**Comment by asarkar** [comment]
This is documented in the README.

> If the output console does not support UTF-8 encoding, the bars may appear as weird characters. If you are running Windows, make sure the terminal encoding is set to UTF-8, or turn off the bars as explained below.
