### ISSUE TITLE
Distributed tracking of build time

### ISSUE THREAD

**Issue by gbazilio** [asarkar/build-time-tracker#26]
Hey there! I was searching to build something similar until I came across your project. The main reason I'd looking to build would be to allow tracking the build time from from the developers machine. So let's say you have multiple squads working on the same project; each squad with multiple developers; so build time may becomes critical at some point.

I was thinking if it would make sense to upload those generated CSV files to some sort of remote storage like S3 (extensible to other providers). Plus adding a few extra properties in the CSV in order to be possible to know the machine configuration or maybe some way that consumers of the plugin can dynamically add columns they would like to have on top of the base columns.

Would you be considering such a thing and willing to take PRs towards that ?

**Comment by asarkar** [comment]
Hi, can’t you take the CSV files and upload to S3, after adding the extra columns? This can be done as a pipeline step in almost all of the major build systems. 

I’m reluctant to turn this plugin to a <protocol of your choice> client; someone else had asked for a HTTP POST functionality before, that I declined and for good reason. The plugin’s job is to report build time, not participate in corporate data crunching. Then there’s the question of the report format; every team has their own.

**Comment by gbazilio** [comment]
Thanks for taking the time @asarkar !

Well, I must agree you have a point there and I'd share some of the same concerns. I needed to ask just in case you were having the exact opposite thoughts of adding such a thing. In any case, I'll keep an eye in this nice repo if your thoughts shifts direction at some point in time. : )
