### ISSUE TITLE
sum does not add up to 100%

### ISSUE THREAD

**Issue by BugsBunnyBR** [asarkar/build-time-tracker#30]
Hey, I ran this plugin in our project and the total sum of the percentages in the time is not 100%, in my case it was 206%.
Is it expected ?

**Comment by asarkar** [comment]
Do you have parallel build enabled?

**Comment by asarkar** [comment]
@BugsBunnyBR This ticket will be closed on Sunday Aug 15 if there's no response from you by then.

**Comment by asarkar** [comment]
Then the behavior is obvious. If 2 tasks take 1 second each running in parallel, and you add them up, you’re going to get double time, not the actual build time.

**Comment by BugsBunnyBR** [comment]
Even though it is obvious, the displayed information is wrong, right ?

**Comment by asarkar** [comment]
The plugin doesn’t calculate total time by adding individual ones, so, no, it’s not wrong. Are you seeing any different?
