### ISSUE TITLE
Support Gradle Configuration Cache

### ISSUE THREAD

**Issue by abendt** [asarkar/build-time-tracker#31]
The plugin cannot be used in a project that also uses the new configuration cache (https://docs.gradle.org/7.2/userguide/configuration_cache.html)

When trying to enable the config cache there is a build failure and this message:

```
FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache problems found in this build.

...
- Plugin 'com.asarkar.gradle.build-time-tracker': registration of listener on 'Gradle.addListener' is unsupported
  See https://docs.gradle.org/7.2/userguide/configuration_cache.html#config_cache:requirements:build_listeners

```

**Comment by asarkar** [comment]
Thanks for the report. I see at the top of the page you linked to:

> This feature is currently highly experimental and not enabled by default.
>
> Not all core Gradle plugins are supported.

Thus, I’ll not support it at this time until the feature is stabilized. I’ll keep the ticket open.

**Comment by asarkar** [comment]
@abendt I've opened a corresponding ticket in the Gradle repo. Can you provide a minimum, reproducible project to demonstrate the issue you're seeing?

**Comment by abendt** [comment]
Sure @asarkar. Her is a demo project: 
https://github.com/abendt/GradleBuildTrackerConfigCache

**Comment by asarkar** [comment]
@pvegh See the linked Gradle ticket.

**Comment by pvegh** [comment]
Not sure what to see there. Support for CC is missing in this plugin

**Comment by asarkar** [comment]
@pvegh This ticket can’t be implemented until the linked ticket is done, it’s clear from the communication above with the reporter. You can enable/disable/remove/add plugin as you please, I don’t need to know.

**Comment by asarkar** [comment]
Hi @pvegh I've already added a comment with additional information in the linked ticket, something that you clearly didn't bother to read. As @abendt said, if you can't wait, feel free to open a PR, or remove the plugin from your project. I don't appreciate your attitude demanding that this ticket be implemented ASAP. If you've anything positive to add to this discussion, you're welcome to comment, otherwise, note that if you keep acting like an entitled brat, you'll be banned from this project.

**Comment by jonnycaley** [comment]
Hey @asarkar Have you considered using build listener lamda's instead of registering a build listener? E.g. 

<img width="666" alt="Screenshot 2022-02-16 at 10 00 22" src="https://user-images.githubusercontent.com/26006896/154240914-238e3d62-3ad3-4e97-939e-b48c77f24b7b.png">

**Comment by asarkar** [comment]
@hiltonc I had actually started going down the path of build time = close - init, but ran into another roadblock. It seems parameters passed to the build service have to be serializable, but a plugin configuration class with Gradle lazy properties isn’t. This turned out to be a blocker issue because without the lazy properties, the plugin cannot capture user provided values when the build starts.

**Comment by hiltonc** [comment]
@asarkar Ah, that makes sense. Bummer.

**Comment by jonnycaley** [comment]
> It seems parameters passed to the build service have to be serializable, but a plugin configuration class with Gradle lazy properties isn’t. This turned out to be a blocker issue because without the lazy properties, the plugin cannot capture user provided values when the build starts.

@asarkar what user provided values are you referring to here?

**Comment by asarkar** [comment]
The ones documented in the README https://github.com/asarkar/build-time-tracker

**Comment by jonnycaley** [comment]
I don't think those values don't need to be lazy as a change in the gradle file where they are located will invalidate the configuration cache entry resulting in a new configuration phase to run which will pick up any new values entered by the user.

**Comment by asarkar** [comment]
> run which will pick up any new values entered by the user

I’m afraid what your think is incorrect according to my experiment. You are welcome to prove otherwise and submit a PR based on this branch https://github.com/asarkar/build-time-tracker/tree/issue-31

**Comment by asarkar** [comment]
As I've mentioned above, a hidden requirement for the build service parameters is to be serializable. I'm not seeing the class `BuildTimeLoggerPluginExtension` in your gist, so it's impossible to say what properties are defined in it. Other than that, I understand what you're trying to do.
If you provide a link to the `BuildTimeLoggerPluginExtension` class, I'll try it out when I find time.

**Comment by jonnycaley** [comment]
I forgot to change that reference in the gist, the `BuildTimeLoggerPluginExtension` should be `PluginExtension` which is defined in the gist.

**Comment by jonnycaley** [comment]
> After reviewing your gist further, it seems you've not actually tried to compile at all, since there are more than one compile errors.

With all due respect, I never said it would compile

>You redeclared the properties in the extension within the build service, which is unmaintainable for a real project with more than one properties. The build service should use the extension as the parameter, not individual properties from the extension.

1. Why is it unmaintainable? Can you not just add another property in the extension and build service parameter?
2. Why should the build service specifically use the extension as parameter?

**Comment by asarkar** [comment]
> Why is it unmaintainable?

The plugin currently supports 7 properties customizable by the user, more may be added as new features are added. It is poor design choice to keep copying them from one class to another. Using the extension for what it is, a container of user parameters, makes the code less prone to error and change.

I don't believe we have anything new here that from what I found 3 months ago. I'm not going to make further attempts until something new comes up, or until Gradle makes an effort to fix their mess.

**Comment by asarkar** [comment]
> I never said it would compile
> I think I replicated the issue on a plugin at work

I think the above statements are contradictory, and you may not have grasped the challenge here.
1. Gradle lazy properties are not serializable. It doesn't matter whether or not they are in an extension POJO or in the build service class.
2. The plugin needs to evaluate properties lazily in order to properly capture user input.

If you've not compiled and ran a plugin, you wouldn't know if any of the above problems exist.

Anyway, I've an idea that I want to try out; I'll comment if something comes out of it.

**Comment by jonnycaley** [comment]
> I think the above statements are contradictory

I never said the gist was the plugin i'm using at work, so they're not contradictory. I don't use this plugin hence why I didn't give you a fully integrated fix.

> The plugin currently supports 7 properties customizable by the user, more may be added as new features are added. It is poor design choice to keep copying them from one class to another.

You're literally now using a `copyParams` function which does what I was doing originally but with a wrapper `BuildTimeTrackerPluginParams` class.

Congrats on getting it to work, and you're welcome for the help.

**Comment by asarkar** [comment]
@abendt @pvegh Are you able to give the release candidate a test run?

**Comment by abendt** [comment]
> @abendt @pvegh Are you able to give the release candidate a test run?

@asarkar looks good, thanks for the effort!
