### ISSUE TITLE
Plugin customizations are ignored if configuration cache is enabled

### ISSUE THREAD

**Issue by dmitry-ryadnenko-izettle** [asarkar/build-time-tracker#44]
**Describe the bug**

Build times are not sorted if build configuration is restored from Gradle configuration cache.

When configuration phase is properly executed (configuration is not restored from the cache) then everything is sorted as expected.

**To Reproduce**

Use `sortBy = com.asarkar.gradle.buildtimetracker.Sort.ASC`
Gradle has configuration cache enabled.
Make sure build configuration is restored from the Gradle configuration cache. By executing the build second time without changing gradle files for example.

**Expected behavior**

Build times are sorted.

**Environment**
 - build-time-tracker plugin version: 4.2.0
 - OS: Mac OS
 - Gradle version: 7.2
 - JDK version: 11

**Comment by asarkar** [comment]
> Make sure build configuration is restored from the Gradle configuration cache

by this, do you mean running with `—configuration-cache`?

**Comment by dmitry-ryadnenko-izettle** [comment]
> > Make sure build configuration is restored from the Gradle configuration cache
> 
> by this, do you mean running with `—configuration-cache`?

Yes

**Comment by asarkar** [comment]
Just so that we are clear, with configuration cache enabled, you’re running the same build multiple times, and none of the output is sorted?

**Comment by asarkar** [comment]
I think I've been able to reproduce the bug, and have an idea what is causing it. For the record, the first execution works as expected, but subsequent executions don't.
I'm looking into it and will report back with more information when I've found a solution.

**Comment by asarkar** [comment]
@dmitry-ryadnenko-izettle I've made a fix on [this branch](https://github.com/asarkar/build-time-tracker/tree/issue-44) as version `4.3.0-rc`. Please verify and let me know. You can find [instructions here](https://github.com/asarkar/build-time-tracker/discussions/46).

Also see discussion https://github.com/asarkar/build-time-tracker/discussions/45 on the topic of Configuration Cache.

**Comment by dmitry-ryadnenko-izettle** [comment]
@asarkar Works like a charm 😊

**Comment by asarkar** [comment]
v4.3.0 has been released.
