### ISSUE TITLE
Provide option to suppress output

### ISSUE THREAD

**Issue by ZivSharifi** [asarkar/build-time-tracker#49]
**Read first**
1. Do not open issues for questions, use https://github.com/asarkar/build-time-tracker/discussions instead.
2. Have you searched in issues and discussions for a similar problem?

**Is your feature request related to a problem? Please describe**
Description of what the problem is.

Hey, i want to have this feature disabled as default, and only show in CI/if user adds a parameter.
I haven't seen this option. 
i think will be helpful.

**Describe the solution you'd like**
Description of what you want to happen.

add configuration for enable (true/false).

**Describe alternatives you've considered**
Description of any alternative solutions or features you've considered.

**Environment**
 - build-time-tracker plugin version: 4.0.3
 - OS: linux
 - Gradle version: 7.2
 - JDK version: 17

**Additional context**

**Comment by asarkar** [comment]
https://github.com/asarkar/build-time-tracker/discussions/48

**Comment by asarkar** [comment]
By design, once added, Gradle plugins are always enabled. You didn’t mention the reason behind your request, and what benefit, in your opinion, it might bring. Feel free to elaborate if you want this issue to be reconsidered.

**Comment by ZivSharifi** [comment]
Hey, thanks for the reply.
Maybe what I mean is toggle the output.
Let’s say a developer doesn’t need this output while developing (unless on specific performance test). But on CI build it is insightful with every run.
So not to disable the feature, but toggle the output on and off.

**Comment by asarkar** [comment]
An option to suppress the output seems reasonable. Can you show how you want to toggle the output depending on the environment?

**Comment by ZivSharifi** [comment]
Sorry for misunderstanding, should I show it via PR? or write the general idea here?

> An option to suppress the output seems reasonable. Can you show how you want to toggle the output depending on the environment?

Sorry for misunderstanding, should I show it via PR? or write the general idea here?

**Comment by asarkar** [comment]
A PR is definitely appreciated but you can also show some code snippet here as to how you intend to use the output.

**Comment by ZivSharifi** [comment]
Hey, sorry, was on vacation fir the past two weeks. will try to attach PR this week.

**Comment by asarkar** [comment]
Before making a PR, I’d like to see how you intend to flip the output based on the environment. Currently there are two output formats, console and CSV. Why don’t you try and switch between them, perhaps based on the presence of an environment variable? If you’re able to do that, then adding another output option is going to be trivial for your use case.
