### ISSUE TITLE
Fail the build if it took too long?

### ISSUE THREAD

**Issue by devvmh** [asarkar/build-time-tracker#50]
My team has some modules that take quite a long time to build. I'd like to enforce a 10 minute build requirement such that builds will fail if they take too long. This plugin seems well-suited to the task; you could just add an optional flag that fails the build if it's above the configured threshold. Default behaviour could continue to be succeeding with info.

My alternative, after some Googling, seems to be to create a build-time-requirement plugin from scratch. It would be a shame though since this plugin already does 90% of what we need.

Let me know your thoughts. Also happy to take a stab at writing the code for this if you'd consider including the feature.

Thanks!

**Comment by asarkar** [comment]
This plugin doesn’t influence the build in any way, it is purely meant for reporting. Failing the build doesn’t fit in its design paradigm, and thus, I don’t think this plugin is a good fit for your requirement. I don’t want the plugin to become a kitchen sink of sort where it aims to do a bunch of things other than what it’s meant for.
Sorry to disappoint you.

**Comment by asarkar** [comment]
Depending on your build system, you may be able to set a timeout on the build job, although not the actual build. For example, Jenkins can do this using a plugin https://plugins.jenkins.io/build-timeout/
